---
title: "Presentation"
author: "noah"
date: "December 4, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

lib <- function(package_name) {
  if (!require(package_name, character.only = TRUE)) {
    install.packages(package_name, repos = "http://cran.us.r-project.org")
    library(package_name, character.only = TRUE)
  }
}

lib('dplyr')
lib('ggplot2')
theme_set(theme_bw())
lib('tidyverse')
lib('pander')
panderOptions('table.split.table', Inf)
```

```{r}
# Load data
animes <- read.csv('../data/clean/animes.csv', header = TRUE, stringsAsFactors = FALSE)
```

# Let's look at the top anime by rating
```{r}
df <- data.frame(Anime = animes$name, Rating = animes$rating, stringsAsFactors = TRUE) # want names as factors for plotting

df <- df[order(df$Rating), ]  # sort by ranking
df$Anime <- factor(df$Anime, levels = df$Anime)  # to retain the order in plot

ggplot(df, aes(x=Anime, y=Rating)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Top Anime Ratings",
       caption="source: MAL dataset") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```

```{r}
# Weeb score
MAX_SCORE <- 10 # We assume students would give their favorite animes this score
MIN_SCORE <- 1 # We assume students would give their least fav animes this score

students <- c("Adriana", "Beau", "David", "Fanny", "Joe", "Kevin", "Lilly (Ralf)", "Lydia", "Mac", "Michael", "Noah", "Richard", "Roger", "Saad", "Shane", "Stephanie", "Ty", "Xiaotai")
fav_animes <- c("Psycho-Pass", "One Punch Man", "Cowboy Bebop", "", "FLCL", "Death Note", "Last Exile", "JoJo no Kimyou na Bouken (TV)", "Pokemon", "Tonari no Totoro", "Ginga Eiyuu Densetsu", "Afro Samurai", "Yuri!!! on Ice", "Dragon Ball Z", "JoJo no Kimyou na Bouken: Diamond wa Kudakenai", "Ouran Koukou Host Club", "Mushishi", "Doraemon (1979)")

calculate_culture_score <- function (fav_anime) {
  anime_from_data <- filter(animes, name == fav_anime)
  if (nrow(anime_from_data) == 0) { # no result
    rating <- MIN_SCORE
  } else {
    rating <- anime_from_data$rating
  }
  culture.score <- (MAX_SCORE - rating)^2
  #if (culture.score < 1) {
    #print("Ah, I see you're a man of culture as well.")
  #}
  return(culture.score)
}

weeb.scores <- sapply(fav_animes, calculate_culture_score)
weeb.scores <- unname(weeb.scores)

df <- data.frame(Student = students, Score = weeb.scores, stringsAsFactors = TRUE) # want names as factors for plotting
  
df <- df[order(df$Score), ]  # sort by ranking
df$Student <- factor(df$Student, levels = df$Student)  # to retain the order in plot

ggplot(df, aes(x=Student, y=Score)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Class Rankings", 
       subtitle="Culture Score", 
       caption="source: In-Class Survey") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```

# The scale is thrown off by Fanny's NA. Let's try again removing the outlier.
```{r}
df <- filter(df, Score < 60)
ggplot(df, aes(x=Student, y=Score)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Class Rankings", 
       subtitle="Squared Error of Favorite Anime Rating", 
       caption="source: In-Class Survey") + 
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```

## Let's explore the distribution of ratings among some different groupings

# First, does type (Movie, TV show,...) matter?
```{r}
animes %>% 
  ggplot(aes(rating, group = type)) +
  geom_density(aes(fill = type), alpha = .4) +
  xlim(0, 10)
```

# Explore the genre too!
```{r}

```
